name: test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - uses: pnpm/action-setup@v4

      - name: install dependencies
        run: pnpm install

      - name: test
        run: |
          GITHUB_ACTIONS= pnpm validate
